const TRACKS = {
  daily:       { id: "daily",       label: "Daily Feel Good",      subtitle: "Functional · Structural · Restorative", purpose: "Spine, core, and posterior chain. The foundation session.",                          sections: DAILY_SECTIONS,    duration: "~25 min" },
  restorative: { id: "restorative", label: "Full Reset", subtitle: "Flow · Circulation · Recovery",         purpose: "Gentle continuous movement for circulation, joint lubrication, and recovery.",      sections: RESTORATIVE_SECTIONS, duration: "~15 min" },
  morning:     { id: "morning",     label: "Morning Refresh",      subtitle: "Gentle · Spinal · Awakening",           purpose: "Seven movements to wake the spine before you look at your phone.",                  sections: MORNING_SECTIONS,  duration: "~8 min"  },
  evening:     { id: "evening",     label: "Better Sleep Stretch",    subtitle: "Restore · Decompress · Release",        purpose: "Lower cortisol, decompress the spine, prepare for sleep.",                          sections: EVENING_SECTIONS,  duration: "~12 min" },
  desk:        { id: "desk",        label: "The Desk Break",          subtitle: "Desk · Posture · Reset",                purpose: "Six movements to undo an hour of sitting. Stand up. Do it now.",                   sections: DESK_SECTIONS,     duration: "~5 min"  },
  screen:      { id: "screen",      label: "Digital Detox",      subtitle: "Neck · Traps · Upper Back",             purpose: "Undo the forward pull of screen time. Seven targeted releases for the neck and shoulder girdle.", sections: SCREEN_SECTIONS, duration: "~12 min" },
  hip:         { id: "hip",         label: "Happy Hips",         subtitle: "Flexors · Rotators · Adductors",        purpose: "Open the hips, free the lower back, restore the range that sitting steals.",        sections: HIP_SECTIONS,      duration: "~18 min" },
  back:        { id: "back",        label: "Lower Back Soother",     subtitle: "Decompress · Release · Restore",        purpose: "For days when the lower back needs care, not challenge. Gentle traction and release.", sections: BACK_SECTIONS,     duration: "~15 min" },
  steady:      { id: "steady",      label: "Stay Steady",            subtitle: "Balance · Proprioception · Control",    purpose: "Train the systems that prevent falls. Simple movements that are deceptively hard to do well.", sections: STEADY_SECTIONS,   duration: "~15 min" },
  freely:      { id: "freely",      label: "Move Freely",            subtitle: "CARS · Joint Health · Synovial Flow",   purpose: "Controlled Articular Rotations and mobility work for every major joint. The WD-40 session.", sections: FREELY_SECTIONS,   duration: "~20 min" },
  transit:     { id: "transit",     label: "In-Transit",           subtitle: "Seated · Circulation · Calm",           purpose: "Four exercises designed for your seat. Keep circulation moving and the nervous system calm during any long journey.",        sections: TRANSIT_SECTIONS,  duration: "~8 min"  },
  travel:      { id: "travel",      label: "Post-Arrival Reset",    subtitle: "Undo Travel · Decompress · Restore",    purpose: "Six movements to undo the posture of travel. Do these as soon as you arrive.",                                           sections: [{label:"Post-Arrival",tag:"PA",purpose:"Six movements to undo the posture of travel. Do these as soon as you reach your hotel or home.",exercises:[{id:1104,name:"Standing Psoas Release",start:"Standing, about to step into a shallow lunge.",sub:"Hip flexors shortened during travel",type:"flow",seconds:60,steps:[{pos:"A",label:"Shallow Lunge",focus:"SETUP",cue:"Step forward into a shallow lunge. Back knee raised or lowered. Torso upright, feet forward."},{pos:"B",label:"Pelvic Tuck & Lean",focus:"STRETCH",cue:"Tuck the pelvis slightly, lean torso toward the front leg. Feel the stretch at the front of the back hip — this is the psoas."},{pos:"C",label:"Hold & Breathe",focus:"RELEASE",cue:"Hold 30–45 seconds each side. With each exhale, allow the hip to sink further. Switch sides."}]},{id:1105,name:"Wall Slides (W to Y)",start:"Standing with your back flat against a wall.",sub:"Activates lower trapezius — fixes luggage shoulder",type:"reps",reps:"10 slow reps",steps:[{pos:"A",label:"Wall Contact",focus:"SETUP",cue:"Head, upper back, and glutes touching the wall. Arms in a W shape — elbows bent, backs of hands against wall."},{pos:"B",label:"Slide to Y",focus:"ACTIVATE",cue:"Keep backs of hands and elbows on the wall and slowly slide arms up to a Y overhead. Do not let contact break."},{pos:"C",label:"Slow Return",focus:"CONTROL",cue:"Lower to W in 3 seconds. Do not shrug. 10 reps. This reverses upper trap dominance from carrying luggage."}]},{id:1106,name:"Open Book Stretch",start:"Lying on your side, knees stacked at 90°.",sub:"Restores thoracic rotation locked after travel",type:"flow",seconds:60,steps:[{pos:"A",label:"Side-Lying Setup",focus:"SETUP",cue:"Lie on your side, hips and knees at 90°, knees stacked. B[... 2147 chars omitted ...]
  anxiety:     { id: "anxiety",    label: "Calm Circuit",       subtitle: "Breathe · Ground · Regulate",         purpose: "Evidence-based techniques that directly shift the nervous system from fight-or-flight to rest and digest.",       sections: ANXIETY_SECTIONS,  duration: "~15 min" },
  stress:      { id: "stress",     label: "Stress",          subtitle: "Discharge · Release · Restore",        purpose: "Complete the stress cycle the body started. Move the cortisol through. Then downshift.",                        sections: STRESS_SECTIONS,   duration: "~18 min" },
  feet:        { id: "feet",        label: "Feet First",             subtitle: "Release · Activate · Strengthen",      purpose: "PT-backed protocol for plantar fasciitis and foot pain. Release the tissue, wake the muscles, load the chain.", sections: FEET_SECTIONS,     duration: "~18 min" },
};
